# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.

pages = [
    "Home" => "index.md",
    # Authored quickstart + guides (package-owned source pages, distinct from
    # the README-derived home page). Add tutorials under `getting-started/`
    # as the package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Installation" => "getting-started/installation.md",
        "Tutorials" => [
            "Convolving distributions" => "getting-started/tutorials/convolving-distributions.md",
            "The difference of two delays" => "getting-started/tutorials/difference-distributions.md",
            "Convolving a timeseries" => "getting-started/tutorials/timeseries-convolution.md",
            "AD backends" => "getting-started/tutorials/ad-backends.md"
        ],
        "FAQ" => "getting-started/faq.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ],
    "Benchmarks" => "benchmarks.md",
    "Development" => [
        "Overview" => "developer/index.md",
        "Contributing" => "developer/contributing.md",
        "Adding a new combination" => "developer/extending.md",
        "Release process" => "developer/release-process.md",
        "Developer FAQ" => "developer/faq.md"
    ],
    "Release notes" => "release-notes.md"
]
