# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.

pages = [
    "Home" => "index.md",
    # Authored quickstart + guides (package-owned source pages, distinct from
    # the README-derived home page). Add tutorials under `getting-started/`
    # as the package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Installation" => "getting-started/installation.md",
        "Tutorials" => [
            "Visualising convolutions" => "getting-started/tutorials/visualising-convolutions.md"
        ],
        "Julia" => "getting-started/julia.md",
        "FAQ" => "getting-started/faq.md",
        "Customising your docs" => "getting-started/customising.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ],
    "Benchmarks" => "benchmarks.md",
    "Development" => [
        "Overview" => "developer/index.md",
        "Contributing" => "developer/contributing.md",
        "Adding a new combination" => "developer/extending.md",
        "Release process" => "developer/release-process.md",
        "Developer FAQ" => "developer/faq.md",
        # Maintainer-facing: kept out of Getting started so a new user's
        # first section is not maintainer noise (kit #136/#156).
        "Infrastructure and template sync" => "getting-started/infrastructure.md"
    ],
    "Release notes" => "release-notes.md"
]
